services:
  # 1. Database (PostgreSQL)
  db:
    image: postgres:16-alpine
    container_name: anor_db_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sheyh12345
      POSTGRES_DB: anor_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Backend (FastAPI)
  backend:
    image: haniyfdev/anor-beck:latest
    container_name: anor_api_container
    restart: always
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - ./anor-beck/.env
    volumes:
      - ./anor-beck/static:/app/static
    depends_on:
      - db

  # 3. FrontEnd (ReactJS)
  frontend:
    image: haniyfdev/anor-front:latest
    container_name: anor_front_container
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
  